
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUMLista : '[' ']'Lista : '[' Conteudo ']'Conteudo : NUMConteudo : Conteudo ',' NUM"
    
_lr_action_items = {'[':([0,],[2,]),'$end':([1,3,6,],[0,-1,-2,]),']':([2,4,5,8,],[3,6,-3,-4,]),'NUM':([2,7,],[5,8,]),',':([4,5,8,],[7,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Lista':([0,],[1,]),'Conteudo':([2,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Lista","S'",1,None,None,None),
  ('Lista -> [ ]','Lista',2,'p_listaVazia','listas_sin_as.py',6),
  ('Lista -> [ Conteudo ]','Lista',3,'p_lista','listas_sin_as.py',9),
  ('Conteudo -> NUM','Conteudo',1,'p_conteudoNum','listas_sin_as.py',12),
  ('Conteudo -> Conteudo , NUM','Conteudo',3,'p_conteudo','listas_sin_as.py',15),
]
